# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: eddacraft.anvil
PackageVersion: '0.13.0-beta'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: anvil.exe
    PortableCommandAlias: anvil
Installers:
  - Architecture: x64
    InstallerUrl: 'https://github.com/eddacraft/anvil/releases/download/v0.13.0-beta/eddacraft-anvil-x86_64-pc-windows-msvc.zip'
    InstallerSha256: '9CA7DADD1F3A082FECCE202B255DB3CD7A3D9DEAC7C1CDD823C4A6F6573DA4D9'
  - Architecture: arm64
    InstallerUrl: 'https://github.com/eddacraft/anvil/releases/download/v0.13.0-beta/eddacraft-anvil-aarch64-pc-windows-msvc.zip'
    InstallerSha256: '14E939248EED201C28A101E3B6B757E63399C6A254E79B410FA5F2CA10484AAD'
ManifestType: installer
ManifestVersion: 1.12.0
